# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhpgvGUX4DJtZdGhH_GQGyCVFD8ItH9J
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load('House Price prediction_model.pkl')

st.title("House Price Prediction App")

# Input fields
area = st.number_input("Area (sq ft)")
bedrooms = st.number_input("Number of Bedrooms")
bathrooms = st.number_input("Number of Bathrooms")

# Predict
if st.button("Predict Price"):
    input_df = pd.DataFrame([[area, bedrooms, bathrooms]], columns=['area', 'bedrooms', 'bathrooms'])
    prediction = model.predict(input_df)[0]
    st.success(f"Predicted Price: ₹{prediction:,.2f}")

